/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/manager/add-movie`; params?: Router.UnknownInputParams; } | { pathname: `/manager/add-showtime`; params?: Router.UnknownInputParams; } | { pathname: `/manager/login`; params?: Router.UnknownInputParams; } | { pathname: `/manager/manage-cinema`; params?: Router.UnknownInputParams; } | { pathname: `/manager/manage-movies`; params?: Router.UnknownInputParams; } | { pathname: `/manager/manage-prices`; params?: Router.UnknownInputParams; } | { pathname: `/manager/manage-showtimes`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/add-movie`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/add-showtime`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/login`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/manage-cinema`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/manage-movies`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/manage-prices`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/manage-showtimes`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/manager/add-movie${`?${string}` | `#${string}` | ''}` | `/manager/add-showtime${`?${string}` | `#${string}` | ''}` | `/manager/login${`?${string}` | `#${string}` | ''}` | `/manager/manage-cinema${`?${string}` | `#${string}` | ''}` | `/manager/manage-movies${`?${string}` | `#${string}` | ''}` | `/manager/manage-prices${`?${string}` | `#${string}` | ''}` | `/manager/manage-showtimes${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/manager/add-movie`; params?: Router.UnknownInputParams; } | { pathname: `/manager/add-showtime`; params?: Router.UnknownInputParams; } | { pathname: `/manager/login`; params?: Router.UnknownInputParams; } | { pathname: `/manager/manage-cinema`; params?: Router.UnknownInputParams; } | { pathname: `/manager/manage-movies`; params?: Router.UnknownInputParams; } | { pathname: `/manager/manage-prices`; params?: Router.UnknownInputParams; } | { pathname: `/manager/manage-showtimes`; params?: Router.UnknownInputParams; };
    }
  }
}
